/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Data.db;
import static GUI.HomePage.labelUsername;
import java.awt.Color;
import java.sql.*;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author hangg
 */
public class LoginPage extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
   

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        
        con = db.mycon();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtemail = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        rememberMe = new javax.swing.JCheckBox();
        btnRegisterhere = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        login_ui = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtemail.setBackground(new java.awt.Color(255, 255, 255));
        txtemail.setBorder(null);
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 310, 20));

        txtpassword.setBackground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(null);
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 300, -1));

        rememberMe.setBackground(new java.awt.Color(255, 255, 255));
        rememberMe.setForeground(new java.awt.Color(255, 255, 255));
        rememberMe.setBorder(null);
        getContentPane().add(rememberMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 20, 20));

        btnRegisterhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterhereMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegisterhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 100, 20));

        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 330, 50));

        login_ui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component/LoginPage.png"))); // NOI18N
        login_ui.setText("jLabel2");
        getContentPane().add(login_ui, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterhereMouseClicked
        // TODO add your handling code here:
        new SignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterhereMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
//        String email = txtemail.getText();
//        String pass = txtpassword.getText();
          Connection con = db.mycon();
          String sql = "SELECT * FROM loguser WHERE email = '"+txtemail.getText()+"' and password = '"+txtpassword.getText()+"'";
       
        Preferences preference;
        boolean rememberPreference;
        preference = Preferences.userNodeForPackage(this.getClass());
        
       
        
        // Put the boolean of the rememberMe preference
        rememberPreference = preference.getBoolean("rememberMe", Boolean.valueOf(""));
        // Check if the check box was selected
        if (rememberPreference){
            // Replace the textField by the preference User and Password who will be stock
            txtemail.setText(preference.get("User", ""));
            txtpassword.setText(preference.get("Password", ""));
            rememberMe.setSelected(rememberPreference);
        }
    
        if (!txtemail.getText().equals("User") && !txtpassword.getText().equals("password")){
            txtemail.setForeground(Color.BLACK);
            txtpassword.setForeground(Color.BLACK);
        }
        
        try {
//            String sql = "SELECT * FROM loguser WHERE  email=? AND password=? AND username=?";
//            pst = con.prepareCall(sql);
//            
//            pst.setString(1, email);
//            pst.setString(2, pass);
            
            
//            rs = pst.executeQuery();
//            
//            if (rs.next()) {
//                JOptionPane.showMessageDialog(rootPane, "Login Successfull");
//                this.setVisible(false);
//                labelUsername.setText(rs.getString(2));
//                new HomePage().setVisible(true);
//                
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Login Failed");
//            }
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql);
                if (rs.next()) {
                    if (rememberMe.isSelected() && !rememberPreference){
                        // Insert into the preference the name
                        preference.put("User", txtemail.getText());
                        preference.put("Password", txtpassword.getText());
                        preference.putBoolean("rememberMe", true);
                    } else if (!rememberMe.isSelected() && rememberPreference){
                        // Reset the preference
                        preference.put("User", "");
                        preference.put("Password", "");
                        preference.putBoolean("rememberMe", false);
                    }
                JOptionPane.showMessageDialog(rootPane, "Login Successfull");
                labelUsername.setText(rs.getString(2));
                this.setVisible(false);
                new HomePage().setVisible(true);
            } else {
                 JOptionPane.showMessageDialog(rootPane, "Login Failed. Try Again!");
                
                }
                
            
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnRegisterhere;
    private javax.swing.JLabel login_ui;
    private javax.swing.JCheckBox rememberMe;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
